name: learning_assistant_demo
description: "学习助手应用"
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # 状态管理
  flutter_bloc: ">=8.1.3 <10.0.0"
  equatable: ^2.0.5
  get_it: ^7.6.0
  provider: ^6.0.5
  
  # 本地存储
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  
  # 网络请求
  http: ^1.1.0
  
  # UI组件
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  flutter_markdown: ^0.6.18
  package_info_plus: ^4.1.0
  flutter_svg: ^2.0.7
  connectivity_plus: ^4.0.2  # 添加此依赖以检测网络状态
  
  # 工具
  intl: ^0.18.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

license: GPL-3.0
repository: https://github.com/xiaonengya/learning_assistant_demo
